# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 张庚
email: zhanggengdyx@gmail.com
description: > # 通过每一天的努力，致力于成为一位优秀的软件工匠.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.zhanggeng.me" # the base hostname & protocol for your site
twitter_username: 如意贝
github_username:  SOFTPOWER1991

# Build settings
markdown: kramdown
